/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodsSlugRouteImport } from './routes/foods/$slug'
import { Route as FoodsFoodRouteImport } from './routes/foods/$food'
import { Route as DemoQueryRouteImport } from './routes/demo/query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsFoodRoute = FoodsFoodRouteImport.update({
  id: '/foods/$food',
  path: '/foods/$food',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoQueryRoute = DemoQueryRouteImport.update({
  id: '/demo/query',
  path: '/demo/query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/query': typeof DemoQueryRoute
  '/foods/$food': typeof FoodsFoodRoute
  '/foods/$slug': typeof FoodsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/query': typeof DemoQueryRoute
  '/foods/$food': typeof FoodsFoodRoute
  '/foods/$slug': typeof FoodsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/query': typeof DemoQueryRoute
  '/foods/$food': typeof FoodsFoodRoute
  '/foods/$slug': typeof FoodsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/query' | '/foods/$food' | '/foods/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/query' | '/foods/$food' | '/foods/$slug'
  id: '__root__' | '/' | '/demo/query' | '/foods/$food' | '/foods/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoQueryRoute: typeof DemoQueryRoute
  FoodsFoodRoute: typeof FoodsFoodRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$slug': {
      id: '/foods/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$food': {
      id: '/foods/$food'
      path: '/foods/$food'
      fullPath: '/foods/$food'
      preLoaderRoute: typeof FoodsFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/query': {
      id: '/demo/query'
      path: '/demo/query'
      fullPath: '/demo/query'
      preLoaderRoute: typeof DemoQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoQueryRoute: DemoQueryRoute,
  FoodsFoodRoute: FoodsFoodRoute,
  FoodsSlugRoute: FoodsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
