/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as DemoQueryRouteImport } from './routes/demo/query'
import { Route as LayoutFoodsFoodRouteImport } from './routes/_layout.foods.$food'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const DemoQueryRoute = DemoQueryRouteImport.update({
  id: '/demo/query',
  path: '/demo/query',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutFoodsFoodRoute = LayoutFoodsFoodRouteImport.update({
  id: '/foods/$food',
  path: '/foods/$food',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/demo/query': typeof DemoQueryRoute
  '/': typeof LayoutIndexRoute
  '/foods/$food': typeof LayoutFoodsFoodRoute
}
export interface FileRoutesByTo {
  '/demo/query': typeof DemoQueryRoute
  '/': typeof LayoutIndexRoute
  '/foods/$food': typeof LayoutFoodsFoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/demo/query': typeof DemoQueryRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/foods/$food': typeof LayoutFoodsFoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/demo/query' | '/' | '/foods/$food'
  fileRoutesByTo: FileRoutesByTo
  to: '/demo/query' | '/' | '/foods/$food'
  id:
    | '__root__'
    | '/_layout'
    | '/demo/query'
    | '/_layout/'
    | '/_layout/foods/$food'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  DemoQueryRoute: typeof DemoQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/demo/query': {
      id: '/demo/query'
      path: '/demo/query'
      fullPath: '/demo/query'
      preLoaderRoute: typeof DemoQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/foods/$food': {
      id: '/_layout/foods/$food'
      path: '/foods/$food'
      fullPath: '/foods/$food'
      preLoaderRoute: typeof LayoutFoodsFoodRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFoodsFoodRoute: typeof LayoutFoodsFoodRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFoodsFoodRoute: LayoutFoodsFoodRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  DemoQueryRoute: DemoQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
